### PR TITLE
Esc cancels target selection

### PR DESCRIPTION
**Pull request by r3a1ay**

### CODE REVIEW

**Comment by clemos** [comment]
Thx
Would you want me to add you as a collaborator ?

**Comment by r3a1ay** [comment]
Why not.
I plan to fix some other issues.

**Comment by clemos** [comment]
I'm curious about you, actually :)
Who are you ? :p

**Comment by r3a1ay** [comment]
I'm new in haxe.
Sublime Text is the best editor for non windows users IMO.
I want to improve it before I'll start new haxe project.
My english is not perfect if you didn't notice. xD
So please check command names, settings names etc in my commits.

**Comment by clemos** [comment]
Where are you from ?

**Comment by r3a1ay** [comment]
Russia.

**Comment by clemos** [comment]
Ok :)
I'm french

**Pull request merged**
