### PR TITLE
'organize imports' feature

### PR DESCRIPTION
**Pull request by r3a1ay**
Sorts imports.
Removes unused and unnecessary imports.

out

### CODE REVIEW

**Comment by fponticelli** [comment]
+1 !

**Comment by clemos** [comment]
Thanks a lot for your contribution :D

**Comment by nadako** [comment]
Unfortunately, this feature doesn't quite work, if you include a whole module which has a lot of types but don't have a main type (or you don't mention it in your code), it removes the import.

Example:


MyModule.hx
```haxe
class SomeOtherName {}
typedef OneMore = {}
```

Main.hx
```haxe
import MyModule; // this import will be removed despite SomeOtherName being used.

class Main {
    static function main() {
        var s = new SomeOtherName();
    }
}
```

**Comment by r3a1ay** [comment]
Thanks.
I'll try to fix that.

**Pull request merged**
